//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Controle_Chave_Negocio.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chave_BD
    {
        public int Codigo { get; set; }
        public short Setor { get; set; }
        public short Situacao { get; set; }
        public string Nome { get; set; }
        public string Numero { get; set; }
        public Nullable<bool> E_Chave_Restrita { get; set; }
    
        public virtual Setor_BD TB_CAD_SETOR { get; set; }
        public virtual Situacao_Chave_BD TB_CAD_SITUACAO_CHAVE { get; set; }
    }
}
