//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Controle_Chave_Negocio.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operador_BD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operador_BD()
        {
            this.TB_CAD_SAIDA_CHAVE = new HashSet<Saida_Chave_BD>();
        }
    
        public int Codigo { get; set; }
        public short Codigo_Plantao { get; set; }
        public short Codigo_Nivel_Operador { get; set; }
        public short Codigo_Setor { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Nome_Operador { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
    
        public virtual Nivel_Operador_BD TB_CAD_NIVEL_OPERADOR { get; set; }
        public virtual Setor_BD TB_CAD_SETOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saida_Chave_BD> TB_CAD_SAIDA_CHAVE { get; set; }
        public virtual Plantao_BD TB_CAD_PLANTAO { get; set; }
    }
}
