//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Controle_Chave_Negocio.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saida_Chave_BD
    {
        public int Codigo { get; set; }
        public int Codigo_Operador { get; set; }
        public int Codigo_Funcionario { get; set; }
        public System.DateTime Data_Saida { get; set; }
        public System.DateTime Data_Devolucao { get; set; }
    
        public virtual Funcionario_BD TB_CAD_FUNCIONARIO { get; set; }
        public virtual Operador_BD TB_CAD_OPERADOR { get; set; }
    }
}
